// models/grouping_models.dart

/// Represents a grouping of track sections by LCS code and meterage
class TrackSectionGrouping {
  final String? id;

  // Grouping identification
  final String lcsCode;
  final double meterageFromLcs;
  final double toleranceMeters;

  // Track sections in this grouping
  final List<int> trackSectionNumbers;
  final int trackSectionCount;

  // Location details
  final String operatingLine;
  final String? roadDirection;
  final String? station;

  // Grouping metadata
  final String? description;
  final bool verified;
  final bool autoGenerated;

  // Timestamps
  final DateTime createdAt;
  final DateTime updatedAt;

  TrackSectionGrouping({
    this.id,
    required this.lcsCode,
    required this.meterageFromLcs,
    this.toleranceMeters = 10,
    required this.trackSectionNumbers,
    int? trackSectionCount,
    required this.operatingLine,
    this.roadDirection,
    this.station,
    this.description,
    this.verified = false,
    this.autoGenerated = true,
    DateTime? createdAt,
    DateTime? updatedAt,
  })  : trackSectionCount = trackSectionCount ?? trackSectionNumbers.length,
        createdAt = createdAt ?? DateTime.now(),
        updatedAt = updatedAt ?? DateTime.now();

  /// Create from JSON
  factory TrackSectionGrouping.fromJson(Map<String, dynamic> json) {
    return TrackSectionGrouping(
      id: json['id'] as String?,
      lcsCode: json['lcs_code'] as String,
      meterageFromLcs: (json['meterage_from_lcs'] as num).toDouble(),
      toleranceMeters: (json['tolerance_meters'] as num?)?.toDouble() ?? 10,
      trackSectionNumbers: (json['track_section_numbers'] as List).cast<int>(),
      trackSectionCount: json['track_section_count'] as int?,
      operatingLine: json['operating_line'] as String,
      roadDirection: json['road_direction'] as String?,
      station: json['station'] as String?,
      description: json['description'] as String?,
      verified: json['verified'] as bool? ?? false,
      autoGenerated: json['auto_generated'] as bool? ?? true,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  /// Convert to JSON
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'lcs_code': lcsCode,
      'meterage_from_lcs': meterageFromLcs,
      'tolerance_meters': toleranceMeters,
      'track_section_numbers': trackSectionNumbers,
      'track_section_count': trackSectionCount,
      'operating_line': operatingLine,
      'road_direction': roadDirection,
      'station': station,
      'description': description,
      'verified': verified,
      'auto_generated': autoGenerated,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  /// Get meterage range
  double get meterageStart => meterageFromLcs - toleranceMeters;
  double get meterageEnd => meterageFromLcs + toleranceMeters;
  double get meterageRange => toleranceMeters * 2;

  /// Get display label for UI
  String get displayLabel {
    return '$lcsCode @ ${meterageFromLcs.toStringAsFixed(1)}m';
  }

  /// Get track section numbers as comma-separated string
  String get trackSectionsDisplay {
    if (trackSectionNumbers.isEmpty) return 'No track sections';
    if (trackSectionNumbers.length <= 3) {
      return trackSectionNumbers.join(', ');
    }
    return '${trackSectionNumbers.take(3).join(', ')}... (+${trackSectionNumbers.length - 3} more)';
  }

  /// Get full track section numbers as comma-separated string
  String get trackSectionsFullDisplay {
    return trackSectionNumbers.join(', ');
  }

  /// Check if a track section number is in this grouping
  bool containsTrackSection(int trackSectionNumber) {
    return trackSectionNumbers.contains(trackSectionNumber);
  }

  /// Check if grouping has any track sections
  bool get isEmpty => trackSectionNumbers.isEmpty;

  /// Check if grouping has track sections
  bool get isNotEmpty => trackSectionNumbers.isNotEmpty;

  /// Check if grouping needs review
  bool get needsReview => !verified && autoGenerated && trackSectionCount > 0;

  /// Copy with modifications
  TrackSectionGrouping copyWith({
    List<int>? trackSectionNumbers,
    bool? verified,
    bool? autoGenerated,
    String? description,
    String? station,
  }) {
    return TrackSectionGrouping(
      id: id,
      lcsCode: lcsCode,
      meterageFromLcs: meterageFromLcs,
      toleranceMeters: toleranceMeters,
      trackSectionNumbers: trackSectionNumbers ?? this.trackSectionNumbers,
      operatingLine: operatingLine,
      roadDirection: roadDirection,
      station: station ?? this.station,
      description: description ?? this.description,
      verified: verified ?? this.verified,
      autoGenerated: autoGenerated ?? this.autoGenerated,
      createdAt: createdAt,
      updatedAt: DateTime.now(),
    );
  }

  /// Add track section to grouping
  TrackSectionGrouping addTrackSection(int trackSectionNumber) {
    if (trackSectionNumbers.contains(trackSectionNumber)) {
      return this;
    }

    final newNumbers = List<int>.from(trackSectionNumbers)
      ..add(trackSectionNumber)
      ..sort();

    return copyWith(
      trackSectionNumbers: newNumbers,
      verified: false,
      autoGenerated: false,
    );
  }

  /// Remove track section from grouping
  TrackSectionGrouping removeTrackSection(int trackSectionNumber) {
    if (!trackSectionNumbers.contains(trackSectionNumber)) {
      return this;
    }

    final newNumbers = List<int>.from(trackSectionNumbers)
      ..remove(trackSectionNumber);

    return copyWith(
      trackSectionNumbers: newNumbers,
      verified: false,
      autoGenerated: false,
    );
  }

  /// Mark as verified
  TrackSectionGrouping markAsVerified() {
    return copyWith(verified: true);
  }

  @override
  String toString() {
    return 'TrackSectionGrouping{$displayLabel: $trackSectionCount sections, verified: $verified}';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is TrackSectionGrouping &&
        other.id == id &&
        other.lcsCode == lcsCode &&
        other.meterageFromLcs == meterageFromLcs;
  }

  @override
  int get hashCode {
    return id.hashCode ^ lcsCode.hashCode ^ meterageFromLcs.hashCode;
  }
}

/// Represents a grouped view for TSR application
class GroupedTrackSectionView {
  final String lcsCode;
  final double meterage;
  final String operatingLine;
  final String? roadDirection;
  final List<TrackSectionInfo> trackSections;

  GroupedTrackSectionView({
    required this.lcsCode,
    required this.meterage,
    required this.operatingLine,
    this.roadDirection,
    required this.trackSections,
  });

  /// Get count of track sections
  int get count => trackSections.length;

  /// Get display label
  String get displayLabel => '$lcsCode @ ${meterage.toStringAsFixed(1)}m → $count sections';

  /// Get all track section numbers
  List<int> get trackSectionNumbers => trackSections.map((ts) => ts.trackSectionNumber).toList();

  /// Get summary string
  String get summary {
    if (trackSections.isEmpty) return 'No track sections';
    if (trackSections.length == 1) return '1 track section: ${trackSections.first.trackSectionNumber}';
    return '$count track sections: ${trackSectionNumbers.take(3).join(", ")}${count > 3 ? "..." : ""}';
  }
}

/// Track section information for grouping
class TrackSectionInfo {
  final int trackSectionNumber;
  final String lcsCode;
  final double chainage;
  final double meterage;
  final String? station;

  TrackSectionInfo({
    required this.trackSectionNumber,
    required this.lcsCode,
    required this.chainage,
    required this.meterage,
    this.station,
  });

  @override
  String toString() {
    return 'TS$trackSectionNumber @ ${meterage.toStringAsFixed(1)}m';
  }
}
